name: mdapy
channels:
  - conda-forge
dependencies:
  - python=3.13
  - lammps
  - pandoc
  - phonopy
  - ase 
  - k3d
  - furo==2024.8.6
  - pip==25.0
  - scikit-build-core==0.10.7
  - cmake==3.31.5
  - nanobind==2.5.0
  - numpy==2.2.2
  - sphinx==8.1.3
  - nbsphinx==0.9.6
  - jupyter_sphinx==0.5.3
