name: mdapy
channels:
  - conda-forge
  - defaults
dependencies:
  - pandoc
  - python=3.9
  - pip>=20.1  # pip is needed as dependency
  - pip:
    - taichi>=1.6.0
    - numpy
    - scipy
    - pandas
    - polars
    - pyarrow
    - matplotlib
    - sphinx
    - sphinx_rtd_theme
    - nbsphinx
    - pybind11