name: mdapy
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pandoc
  - cmake
  - ninja
  - cxx-compiler  
  - pip
  - setuptools
  - wheel
  - pip:
    - scikit-build-core>=0.4.3
    - nanobind>=1.3.2
    - numpy
    - polars>=1.8.0
    - matplotlib
    - sphinx
    - pydata_sphinx_theme
    - nbsphinx
    - ipython  